version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:xZ3R9n7K2tL8vB5mY6QpJ4wC1hE0aUdG@mongo:27019/clients_db?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27019
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: xZ3R9n7K2tL8vB5mY6QpJ4wC1hE0aUdG
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27019:27019"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xZ3R9n7K2tL8vB5mY6QpJ4wC1hE0aUdG
      MONGO_INITDB_DATABASE: clients_db
    command: mongod --port 27019
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "-u", "root", "-p", "xZ3R9n7K2tL8vB5mY6QpJ4wC1hE0aUdG", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
